language: python
env:
 - PYTHONPATH=`pwd`
python:
  - "3.6"
  - "nightly"
install:
  - "pip install pytest"
  - "pip install -r requirements.txt"
script: cd section7/starter_code/ && python -m pytest
only:
  - braches
